export const FIRE_EMPLOYEE = 'FIRE_EMPLOYEE';
export const SPARE_EMPLOYEE = 'SPARE_EMPLOYEE';

export const CREATE_PLAN = 'CREATE_PLAN';
export const SUBMIT_PLAN = 'SUBMOT_PLAN';
export const DELETE_PLAN = 'DELETE_PLAN';
export const SELECT_PLAN = 'SELECT_PLAN';

export const COLLECT_SLAVES_REQUEST = 'COLLECT_SLAVES_REQUEST';
export const COLLECT_SLAVES_SUCCESS = 'COLLECT_SLAVES_SUCCESS';
export const COLLECT_SLAVES_FAILURE = 'COLLECT_SLAVES_FAILURE';
